camera:
  type: mock
  width: 640
  height: 480
  fps: 30
  enable_depth: true

actuator:
  type: mock
  steering_channel: 0
  throttle_channel: 1
  steering_min_angle: 30
  steering_max_angle: 120
  steering_center_angle: 75
  steering_trim: 0.0
  throttle_max: 0.4
